export const nfts = [
  {
    id: 21,
    name: "Haze Monkey",
    creator: "HAZE",
    price: 5.0,
    auction: "5",
    image: "/haze2.png",
  },
  {
    id: 0o1,
    name: "Bored Ape Yacht Club",
    creator: "BAYC",
    price: 20.3,
    auction: "5",
    image: "/bayc-1.png",
  },
  {
    id: 0o6,
    name: "Meta Angle",
    creator: "META",
    price: 20.3,
    auction: "5",
    image: "/meta1.png",
  },
  {
    id: 21,
    name: "Haze Monkey",
    creator: "HAZE",
    price: 5.0,
    auction: "5",
    image: "/haze1.png",
  },
  {
    id: 0o2,
    name: "Bored Ape Yacht Club",
    creator: "BAYC",
    price: 8.5,
    auction: "5",
    image: "/bayc-2.webp",
  },
  {
    id: 0o3,
    name: "Haze Monkey",
    creator: "BAYC",
    price: 10.8,
    auction: "5",
    image: "/bayc-3.webp",
  },
  {
    id: 10,
    name: "Meta Angle",
    creator: "META",
    price: 20.3,
    auction: "5",
    image: "/meta2.png",
  },
  {
    id: 0o4,
    name: "Bored Ape Yacht Club",
    creator: "BAYC",
    price: 5.0,
    auction: "5",
    image: "/bayc-4.webp",
  },
];
